config/routes.rb
PersonLog::Application.routes.draw do

  resources :images


  resources :galleries


  mount Tolk::Engine => '/tolk', :as => 'tolk'
  resources :permissions
  resources :visits
  get "moderators/versions"
  get "moderators/dashboard"
  get "/pages/:id" => 'pages#show', :as => :page
  get "import" => "import#index"
  get "import/twitter"
  get "import/facebook"
  get "import/linkedin"
  get "import/github"
  get "import/google"
  get "import/linkedin_profile"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "/persons/search" => "users#search"
  get "/persons/map" => "users#map"
  get "/persons/tags" => "users#tags"
  get "/friends" => "users#friends"
  get "/persons/typeahead" => "users#typeahead"
  get "/persons/list" => "users#list"
  get "/persons/manage" => "users#manage"
  match "/persons/update_address/:id/:address" => "users#update_address"

  get 'tags/:tag', :to => 'users#index', :as => :tag
  resources :queries

  devise_for :users, :path => "persons", :controllers => {:registrations => 'registrations',
                                                          :invitations => 'users/invitations',
                                                          :confirmations => "confirmations",
                                                          :omniauth_callbacks => "users/omniauth_callbacks"}
  #resources :users, :path => 'persons', only: [:show, :index, :edit, :update]
  match 'persons/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'persons/bulk_action' => 'users#bulk_action', :via => :get, :as => :bulk_user_action
  resources :users, :path => 'persons' do
    get 'invite', :on => :member
  end

  authenticated :user do
    root :to => 'home#index'
  end

  devise_scope :user do
    root :to => "registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  resources :authentications
  resources :positions
  resources :educations
  resources :companies
  resources :urls
  resources :newsletters do
    member { post :deliver }
  end
  match "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "versions" => "versions#index"
  get "versions/:id" => "versions#show", :as => :version
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  summary    :text
#  start_date :date
#  is_current :boolean
#  company_id :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  end_date   :date
#

class Position < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  has_paper_trail
  attr_accessible :id, :company_id, :is_current, :start_date, :end_date, :summary, :name, :user_id
  resourcify
  validates_presence_of :name
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  add_breadcrumb :positions, :positions_path

  # GET /positions
  # GET /positions.json
  def index
    add_breadcrumb :list
    @positions = Position.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    add_breadcrumb :details
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    add_breadcrumb :new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    add_breadcrumb :edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.haml
= simple_form_for @position, :html => { :class => 'form-vertical' } do |f|
  = f.input :name, :autofocus => true
  = f.input :summary, :as => :text, :input_html => { :cols => 50, :rows => 5, :style => 'width: 635px; height: 200px;' }
  .input-append.date.datepicker{'data-date-format' => 'yyyy-mm-dd'}
    = f.label :start_date
    = f.text_field :start_date, :class => ''
    %span.add-on
      %i.icon-calendar

  .input-append.date.datepicker{'data-date-format' => 'yyyy-mm-dd'}
    = f.label :end_date
    = f.text_field :end_date, :class => ''
    %span.add-on
      %i.icon-calendar
  = f.input :is_current
  = f.association :company, as: :radio_buttons
  = f.input :user_id, :as => :hidden, :input_html => {:value => current_user.id}
  .form-actions
    = f.button :submit, :class => 'btn-primary btn-af'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), positions_path, :class => 'btn'

app/views/positions/edit.html.haml
- model_class = Position

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'educations/sidebar'

app/views/positions/index.html.haml
- model_class = Position

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand=t '.title', :default => model_class.model_name.human.pluralize + ' Listing'
          = link_to t('.new', :default => t("helpers.links.new")), new_position_path, :class => 'btn btn-af btn-mini pull-right'

    %table.table.table-striped.datatable.table-bordered
      %thead
        %tr
          %th= model_class.human_attribute_name(:name)
          %th= model_class.human_attribute_name(:start_date)
          %th= model_class.human_attribute_name(:is_current)
          %th= model_class.human_attribute_name(:company_id)
          %th= t "helpers.actions"
      %tbody
        - @positions.each do |position|
          %tr
            %td= link_to position.name, position_path(position)
            %td= position.start_date
            %td= position.is_current
            %td= link_to position.company.name, position.company
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_position_path(position), :class => 'btn btn-mini'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), position_path(position), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

.span3.right-sidebar-fluid
  = render 'positions/sidebar'

app/views/positions/new.html.haml
- model_class = Position

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'positions/sidebar'

app/views/positions/show.html.haml
- model_class = Position

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => model_class.model_name.human


    %p
      %strong= model_class.human_attribute_name(:name) + ':'
      %br
      = @position.name
    %p
      %strong= model_class.human_attribute_name(:summary) + ':'
      %br
      = @position.summary
    %p
      %strong= model_class.human_attribute_name(:start_date) + ':'
      %br
      = @position.start_date
    %p
      %strong= model_class.human_attribute_name(:end_date) + ':'
      %br
      = @position.end_date if @position.end_date
    %p
      %strong= model_class.human_attribute_name(:is_current) + ':'
      %br
      = @position.is_current
    %p
      %strong= model_class.human_attribute_name(:company_id) + ':'
      %br
      = link_to @position.company.name, company_path(@position.company)
    %p
      %strong= model_class.human_attribute_name(:user_id) + ':'
      %br
      = link_to @position.user.name, user_path(@position.user)

    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), positions_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_position_path(@position), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), position_path(@position), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.span3.right-sidebar-fluid
  = render 'positions/sidebar'