config/routes.rb
PersonLog::Application.routes.draw do

  resources :images


  resources :galleries


  mount Tolk::Engine => '/tolk', :as => 'tolk'
  resources :permissions
  resources :visits
  get "moderators/versions"
  get "moderators/dashboard"
  get "/pages/:id" => 'pages#show', :as => :page
  get "import" => "import#index"
  get "import/twitter"
  get "import/facebook"
  get "import/linkedin"
  get "import/github"
  get "import/google"
  get "import/linkedin_profile"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "/persons/search" => "users#search"
  get "/persons/map" => "users#map"
  get "/persons/tags" => "users#tags"
  get "/friends" => "users#friends"
  get "/persons/typeahead" => "users#typeahead"
  get "/persons/list" => "users#list"
  get "/persons/manage" => "users#manage"
  match "/persons/update_address/:id/:address" => "users#update_address"

  get 'tags/:tag', :to => 'users#index', :as => :tag
  resources :queries

  devise_for :users, :path => "persons", :controllers => {:registrations => 'registrations',
                                                          :invitations => 'users/invitations',
                                                          :confirmations => "confirmations",
                                                          :omniauth_callbacks => "users/omniauth_callbacks"}
  #resources :users, :path => 'persons', only: [:show, :index, :edit, :update]
  match 'persons/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'persons/bulk_action' => 'users#bulk_action', :via => :get, :as => :bulk_user_action
  resources :users, :path => 'persons' do
    get 'invite', :on => :member
  end

  authenticated :user do
    root :to => 'home#index'
  end

  devise_scope :user do
    root :to => "registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  resources :authentications
  resources :positions
  resources :educations
  resources :companies
  resources :urls
  resources :newsletters do
    member { post :deliver }
  end
  match "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "versions" => "versions#index"
  get "versions/:id" => "versions#show", :as => :version
end

app/models/visit.rb
# == Schema Information
#
# Table name: visits
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  ip         :string(255)
#  ua         :string(255)
#  created    :datetime
#  visitor_id :integer
#

class Visit < ActiveRecord::Base
  belongs_to :user
  attr_accessible :created, :ip, :ua, :user_id, :visitor_id
  paginates_per 22
  resourcify
  default_scope order('created DESC')

  before_save :init_data

  def init_data
    self.created ||= DateTime.now if new_record?
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  add_breadcrumb :visits, :visits_path

  # GET /visits
  # GET /visits.json
  def index
    add_breadcrumb :list

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: VisitsDatatable.new(view_context) }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    add_breadcrumb :details
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    add_breadcrumb :new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    add_breadcrumb :edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.haml
= simple_form_for @visit, :html => { :class => 'form-horizontal' } do |f|
  = f.association :user
  = f.input :ip
  = f.input :ua
  = f.input :created
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), visits_path, :class => 'btn'

app/views/visits/_sidebar.html.haml
- if user_signed_in?
  .row-fluid
    .span12
      .well
        .navbar.navbar-heading
          .navbar-inner
            .container
              %span.brand= "Import Friends"
        %ul.nav.nav-tabs.nav-stacked
          %li= link_to 'Facebook <i class="icon-facebook float-right"></i>'.html_safe, import_facebook_path
          %li= link_to 'LinkedIn <i class="icon-linkedin float-right"></i>'.html_safe, import_linkedin_path
          %li= link_to 'GitHub <i class="icon-github float-right"></i>'.html_safe, import_github_path
          %li= link_to 'Twitter <i class="icon-twitter float-right"></i>'.html_safe, import_twitter_path
  %br.clearfix
  .row-fluid
    .span12
      .well
        .navbar.navbar-heading
          .navbar-inner
            .container
              %span.brand= 'Navigation'
        %ul.nav.nav-tabs.nav-stacked
          %li= link_to 'Who Viewed me <i class="icon-group float-right"></i>'.html_safe, visits_path
          %li= link_to 'People I Viewed <i class="icon-group float-right"></i>'.html_safe, visits_path(type: 'my')
          %li= link_to 'My Profile <i class="icon-user float-right"></i>'.html_safe, edit_user_registration_path
          %li= link_to 'My Educations <i class="icon-book float-right"></i>'.html_safe, educations_path
          %li= link_to 'My Positions <i class="icon-user-md float-right"></i>'.html_safe, positions_path
          %li= link_to 'My Search history <i class="icon-time float-right"></i>'.html_safe, queries_path
          %li= link_to 'My URLs <i class="icon-globe float-right"></i>'.html_safe, urls_path
  %br.clearfix

app/views/visits/_visits.html.haml
- if params[:type]
  %table.datatable.ajaxed.display.table.table-striped.table-bordered{"data-source"=> visits_url(format: "json", type: "my")}
    %thead
      %tr
        %th{:width => 10}= '<input type="checkbox" class="toggle">'.html_safe
        %th= "IP Address"
        %th= "Person"
        %th= "Browser and OS"
        %th= "created"
        %th= t '.actions', :default => t("helpers.actions.actions")
    %tbody
- else
  %table.datatable.ajaxed.display.table.table-striped.table-bordered{"data-source"=> visits_url(format: "json")}
    %thead
      %tr
        %th{:width => 10}= '<input type="checkbox" class="toggle">'.html_safe
        %th= "IP Address"
        %th= "visitor"
        %th= "Browser and OS"
        %th= "created"
        %th= t '.actions', :default => t("helpers.actions.actions")
    %tbody

app/views/visits/edit.html.haml
- model_class = Visit

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'visits/sidebar'

app/views/visits/index.html.haml
- model_class = Visit

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= params[:type].present?? 'people I viewed' : 'who viewed my profile'
    = render 'visits'

.span3.right-sidebar-fluid
  = render 'visits/sidebar'

app/views/visits/new.html.haml
- model_class = Visit

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'visits/sidebar'

app/views/visits/show.html.haml
- model_class = Visit

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => model_class.model_name.human

    %p
      %strong= model_class.human_attribute_name(:user_id) + ':'
      %br
      = link_to @visit.user.name, @visit.user
    %p
      %strong= model_class.human_attribute_name(:ip) + ':'
      %br
      = @visit.ip
    %p
      %strong= model_class.human_attribute_name(:ua) + ':'
      %br
      = @visit.ua
    %p
      %strong= model_class.human_attribute_name(:created) + ':'
      %br
      = @visit.created

    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), visits_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_visit_path(@visit), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), visit_path(@visit), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.span3.right-sidebar-fluid
  = render 'visits/sidebar'