config/routes.rb
PersonLog::Application.routes.draw do

  resources :images


  resources :galleries


  mount Tolk::Engine => '/tolk', :as => 'tolk'
  resources :permissions
  resources :visits
  get "moderators/versions"
  get "moderators/dashboard"
  get "/pages/:id" => 'pages#show', :as => :page
  get "import" => "import#index"
  get "import/twitter"
  get "import/facebook"
  get "import/linkedin"
  get "import/github"
  get "import/google"
  get "import/linkedin_profile"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "/persons/search" => "users#search"
  get "/persons/map" => "users#map"
  get "/persons/tags" => "users#tags"
  get "/friends" => "users#friends"
  get "/persons/typeahead" => "users#typeahead"
  get "/persons/list" => "users#list"
  get "/persons/manage" => "users#manage"
  match "/persons/update_address/:id/:address" => "users#update_address"

  get 'tags/:tag', :to => 'users#index', :as => :tag
  resources :queries

  devise_for :users, :path => "persons", :controllers => {:registrations => 'registrations',
                                                          :invitations => 'users/invitations',
                                                          :confirmations => "confirmations",
                                                          :omniauth_callbacks => "users/omniauth_callbacks"}
  #resources :users, :path => 'persons', only: [:show, :index, :edit, :update]
  match 'persons/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'persons/bulk_action' => 'users#bulk_action', :via => :get, :as => :bulk_user_action
  resources :users, :path => 'persons' do
    get 'invite', :on => :member
  end

  authenticated :user do
    root :to => 'home#index'
  end

  devise_scope :user do
    root :to => "registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  resources :authentications
  resources :positions
  resources :educations
  resources :companies
  resources :urls
  resources :newsletters do
    member { post :deliver }
  end
  match "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "versions" => "versions#index"
  get "versions/:id" => "versions#show", :as => :version
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id           :integer          not null, primary key
#  subject      :string(255)
#  delivered_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Newsletter < ActiveRecord::Base
  has_paper_trail
  attr_accessible :delivered_at, :subject
  resourcify
  validates_presence_of :subject

  def self.deliver(id)
    newsletter = find(id)
    # raise "Oops"
    sleep 30 # simulate long newsletter delivery
    newsletter.update_attribute(:delivered_at, Time.zone.now)
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb :newsletters, :newsletters_path

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
    add_breadcrumb :list
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    add_breadcrumb :details
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new
    add_breadcrumb :new
    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    add_breadcrumb :edit
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  def deliver
    QC.enqueue "Newsletter.deliver", params[:id]
    redirect_to newsletters_url, notice: "Delivering newsletter."
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.haml
= simple_form_for @newsletter, :html => { :class => 'form-horizontal' } do |f|
  = f.input :subject
  = f.input :delivered_at
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), newsletters_path, :class => 'btn'

app/views/newsletters/_sidebar.html.haml
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            %span.brand=t("common.widget.title")
      %ul.nav.nav-tabs.nav-stacked
        %li= link_to 'Who Viewed me <i class="icon-group float-right"></i>'.html_safe, visits_path
        %li= link_to 'Person Details <i class="icon-eye-open float-right"></i>'.html_safe, nil
        %li= link_to 'Faborite <i class="icon-heart float-right"></i>'.html_safe, nil
        %li= link_to 'More Like This <i class="icon-group float-right"></i>'.html_safe, nil
        %li= link_to 'Bookmark <i class="icon-bookmark float-right"></i>'.html_safe, nil

app/views/newsletters/edit.html.haml
- model_class = Newsletter

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")

    = render :partial => "form"

.span3
  = render 'newsletters/sidebar'

app/views/newsletters/index.html.haml
- model_class = Newsletter

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand=t '.title', :default => model_class.model_name.human.pluralize + ' Listing'
          = link_to t('.new', :default => t("helpers.links.new")), new_newsletter_path, :class => 'btn btn-af btn-mini pull-right'

    %table.table.table-striped
      %thead
        %tr
          %th= model_class.human_attribute_name(:subject)
          %th= model_class.human_attribute_name(:delivered_at)
          %th= model_class.human_attribute_name(:created_at)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody
        - @newsletters.each do |newsletter|
          %tr
            %td= link_to newsletter.subject, newsletter_path(newsletter)
            %td= newsletter.delivered_at
            %td=l newsletter.created_at
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_newsletter_path(newsletter), :class => 'btn btn-mini'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), newsletter_path(newsletter), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
              = link_to "Deliver Newsletter", deliver_newsletter_path(newsletter), method: :post, :class => 'btn btn-af btn-mini'


.span3
  = render 'newsletters/sidebar'

app/views/newsletters/new.html.haml
- model_class = Newsletter

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

    = render :partial => "form"

.span3
  = render 'newsletters/sidebar'

app/views/newsletters/show.html.haml
- model_class = Newsletter

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => model_class.model_name.human

    %p
      %strong= model_class.human_attribute_name(:subject) + ':'
      %br
      = @newsletter.subject
    %p
      %strong= model_class.human_attribute_name(:delivered_at) + ':'
      %br
      = @newsletter.delivered_at

    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), newsletters_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_newsletter_path(@newsletter), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), newsletter_path(@newsletter), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.span3
  = render 'newsletters/sidebar'