config/routes.rb
PersonLog::Application.routes.draw do

  resources :images


  resources :galleries


  mount Tolk::Engine => '/tolk', :as => 'tolk'
  resources :permissions
  resources :visits
  get "moderators/versions"
  get "moderators/dashboard"
  get "/pages/:id" => 'pages#show', :as => :page
  get "import" => "import#index"
  get "import/twitter"
  get "import/facebook"
  get "import/linkedin"
  get "import/github"
  get "import/google"
  get "import/linkedin_profile"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "/persons/search" => "users#search"
  get "/persons/map" => "users#map"
  get "/persons/tags" => "users#tags"
  get "/friends" => "users#friends"
  get "/persons/typeahead" => "users#typeahead"
  get "/persons/list" => "users#list"
  get "/persons/manage" => "users#manage"
  match "/persons/update_address/:id/:address" => "users#update_address"

  get 'tags/:tag', :to => 'users#index', :as => :tag
  resources :queries

  devise_for :users, :path => "persons", :controllers => {:registrations => 'registrations',
                                                          :invitations => 'users/invitations',
                                                          :confirmations => "confirmations",
                                                          :omniauth_callbacks => "users/omniauth_callbacks"}
  #resources :users, :path => 'persons', only: [:show, :index, :edit, :update]
  match 'persons/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'persons/bulk_action' => 'users#bulk_action', :via => :get, :as => :bulk_user_action
  resources :users, :path => 'persons' do
    get 'invite', :on => :member
  end

  authenticated :user do
    root :to => 'home#index'
  end

  devise_scope :user do
    root :to => "registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  resources :authentications
  resources :positions
  resources :educations
  resources :companies
  resources :urls
  resources :newsletters do
    member { post :deliver }
  end
  match "versions/:id/revert" => "versions#revert", :as => "revert_version"
  get "versions" => "versions#index"
  get "versions/:id" => "versions#show", :as => :version
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id          :integer          not null, primary key
#  industry    :string(255)
#  name        :string(255)
#  description :text
#  location    :string(255)
#  size        :string(255)
#  ctype       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Company < ActiveRecord::Base
  has_many :positions
  attr_accessible :id, :industry, :name, :size, :ctype, :positions, :location, :description, :position_ids
  has_paper_trail
  resourcify
  validates :name, :presence => true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource
  add_breadcrumb :companies, :companies_path

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    add_breadcrumb :list
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    add_breadcrumb :details
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    add_breadcrumb :new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    add_breadcrumb :edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= simple_form_for @company, :html => { :class => 'form-vertical' } do |f|
  = f.input :name, :autofocus => true
  = f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 5, :style => 'width: 635px; height: 200px;' }
  = f.input :industry
  = f.input :location
  = f.input :size
  = f.input :ctype
  = f.association :positions, :as => :check_boxes
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), companies_path, :class => 'btn'

app/views/companies/_sidebar.html.haml
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            %span.brand=t("common.widget.title")
      %ul.nav.nav-tabs.nav-stacked
        %li= link_to 'Who Viewed me <i class="icon-group float-right"></i>'.html_safe, visits_path
        %li= link_to 'Facebook <i class="icon-facebook float-right"></i>'.html_safe, import_facebook_path
        %li= link_to 'LinkedIn <i class="icon-linkedin float-right"></i>'.html_safe, import_linkedin_path
        %li= link_to 'GitHub <i class="icon-github float-right"></i>'.html_safe, import_github_path
        %li= link_to 'Twitter <i class="icon-twitter float-right"></i>'.html_safe, import_twitter_path

app/views/companies/edit.html.haml
- model_class = Company

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'companies/sidebar'

app/views/companies/index.html.haml
- model_class = Company

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand=t '.title', :default => model_class.model_name.human.pluralize + ' Listing'
          = link_to raw('<i class="icon-plus-sign"></i> ' + t('.new', :default => t("helpers.links.new"))),
          new_company_path,
          :class => 'btn btn-af btn-mini pull-right'
    %table.datatable.table.table-striped.table-bordered
      %thead
        %tr
          %th= model_class.human_attribute_name(:name)
          %th= model_class.human_attribute_name(:industry)
          %th= model_class.human_attribute_name(:ctype)
          %th= model_class.human_attribute_name(:created_at)
          %th=t '.actions', :default => t("helpers.actions")
      %tbody
        - @companies.each do |company|
          %tr
            %td= link_to company.name, company_path(company)
            %td= company.industry
            %td= company.ctype
            %td=l company.created_at, format: :short
            %td
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(company), :class => 'btn btn-mini'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(company), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'



.span3.right-sidebar-fluid
  = render 'companies/sidebar'

app/views/companies/new.html.haml
- model_class = Company

.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
    = render :partial => "form"

.span3.right-sidebar-fluid
  = render 'companies/sidebar'

app/views/companies/show.html.haml
- model_class = Company


.span9
  = render_breadcrumbs
  .well
    .navbar.navbar-heading
      .navbar-inner
        .container
          %span.brand= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")

    %p
      %strong= model_class.human_attribute_name(:name) + ':'
      %br
      = @company.name
    %p
      %strong= model_class.human_attribute_name(:description) + ':'
      %br
      = @company.description
    %p
      %strong= model_class.human_attribute_name(:industry) + ':'
      %br
      = @company.industry
    %p
      %strong= model_class.human_attribute_name(:location) + ':'
      %br
      = @company.location
    %p
      %strong= model_class.human_attribute_name(:size) + ':'
      %br
      = @company.size
    %p
      %strong= model_class.human_attribute_name(:ctype) + ':'
      %br
      = @company.ctype

    %p
      %strong= model_class.human_attribute_name(:positions) + ':'
      %br
      - for position in @company.positions.all({:limit => 5})
        = link_to "<i class=\"icon-user\"></i> #{position.name}".html_safe, position_path(position), :class => 'btn btn-mini'


    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), companies_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_company_path(@company), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), company_path(@company), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'


.span3.right-sidebar-fluid
  = render 'companies/sidebar'